general:
  join delay seconds: 3
  ignore:
    - lobby
  enqueue message:
    - "&bYou are now &e$position &bin the queue to join &a$server&b. priority &5$priority"

levels:
  - priority: 100
    permission: queue.priority.staff
    name: Highest
  - priority: 10
    permission: queue.priority.boi
    name: Some Text